### ISSUE TITLE
ECOS BB segfaults when no integer/boolean variables

### ISSUE THREAD

**Issue by SteveDiamond** [embotech/ecos#101]
ECOS BB segfaults if both num_bool_vars=0 and num_int_vars=0. There should be at least an error instead of a segfault. Ideally it would just call normal ecos and solve the problem.

Here's some code to trigger the issue:
```
from cvxpy import *
x = Variable()
prob = Problem(Minimize(x), [x >= 2])
prob.solve(solver=ECOS_BB)
```

**Comment by hanwang** [comment]
Hi Steve, 

Can you link me to the ecos_bb wrapper in CVXPY? The way the python interface is implemented, it should switch automatically between ecos_bb and ecos depending on if you pass in the lists of integer and boolean variables.

**Comment by SteveDiamond** [comment]
It's here:

https://github.com/cvxgrp/cvxpy/blob/master/cvxpy/problems/solvers/ecos_bb_intf.py

It's passing in empty lists for bool_var_idx and int_var_idx.

**Comment by hanwang** [comment]
Thanks Steve, please pull the lastest ecos-python and rebuild. I just pushed a patch that should solve this issue.

**Comment by hanwang** [comment]
Can I close this issue now?

**Comment by SteveDiamond** [comment]
Yes, that's fine.
