### ISSUE TITLE
The equilibration scheme destroys the quality of the result.

### ISSUE THREAD

**Issue by tiagoakle** [embotech/ecos#104]
Apparently the equilibration as implemented can destroy the results:
loading the lp_agg matrix (from the UFget package not the .h file) 
forming the LP problem and solving with 

  [x,y,info,s,z] = ecos(c,G,h,dims,A,b);
  pres = norm([A*x-b;G*x+s-h]);
  dres = norm(A'*y+G'*z+c);
  comp = s'*z;

results in the residuals
pres = 5.805e+05, dres=3.557e+01 comp=6.982e-06.

If we turn off equilibration we get 
pres=4.777e-09, dres=8.618e-09 comp=4.348e-06  
however the .h file test for this same matrix fails with numerical problems 
and lp_agg2 returns nan.

Im working on implementing an equilibration scheme that works better. 
We should also check the size of the residuals in some of the tests, just to 
make sure changes in the equilibration schemes won't affect the quality 
of the results.

**Comment by adomahidi** [comment]
Thanks, @tiagoakle . Overall ecos works better with equilibration, but it'd be of course great if you know of a scheme that at least does not produce worse results than without.

**Comment by mcg1969** [comment]
I agree that equilibration is usually a good choice. But I have encountered problems in CVX with some models that yield significantly different results due to scaling. 

In my view, the final error measures ought to be presented in terms of the unscaled problem. That is, after all, the problem presented to the solver. 

Perhaps one approach would be to solve the problem initially with equilibration, then look at the unscaled residuals; if they are significantly worse than expected, re-run without equilibration, hot-starting from a recent solution.

**Comment by tiagoakle** [comment]
@mcg1969 @adomahidi. I ran the following experiment:
Solved the first 10 standard form lps in LPnetlib with equilibration and 
evaluate the residuals and complementarity. Then repeat without equilibration.

You will see that with equilibration, ecos in fact returns optimal for all 
but the linear residuals for *all* problems are too large. 

On the other hand without equilibration ecos fails at 2 problems 
but the ones it does solve, have more meaningful answers.

Some part of the equilibration is broken, I'm afraid the tests don't 
look at the residuals, and we've been measuring success mostly 
by the number of problems correctly categorized as optimal, infeasible, 
etc. 

Results:
 //LP With Ruiz scaling
     Problem name Iter Flag Norm Residual Complementarity
       LPnetlib/lp_25fv47,  30,   0, 3.3e+03, 7.3e-06 
       LPnetlib/lp_adlittle,  13,   0, 1.4e+04, 5.0e-06 
          LPnetlib/lp_afiro,    9,   0, 9.8e+01, 1.1e-07 
           LPnetlib/lp_agg,  98,   0, 5.8e+05, 7.0e-06 
         LPnetlib/lp_agg2,  30,   0, 2.5e+05, 3.6e-06 
         LPnetlib/lp_agg3,  30,   0, 2.6e+05, 1.2e-05 
      LPnetlib/lp_bandm,  21,   0, 7.3e+02, 7.2e-08 
  LPnetlib/lp_beaconfd,  12,   0, 9.2e+04, 5.3e-08 
        LPnetlib/lp_blend,  12,   0, 7.8e+01, 7.6e-08 
          LPnetlib/lp_bnl1,  62,   0, 8.5e+02, 1.3e-06 

 //LP Without Ruiz scaling
        Problem name Iter Flag Norm Residual Complementarity
   LPnetlib/lp_25fv47,  33,      0, 2.7e-08, 7.5e-08 
    LPnetlib/lp_adlittle,  12,      0, 3.2e-07, 9.0e-05 
        LPnetlib/lp_afiro,   9,      0, 4.6e-09, 5.6e-08 
         LPnetlib/lp_agg,  92,     0, 9.9e-09, 4.3e-06 
       LPnetlib/lp_agg2, 100,  10, 4.6e-06, 8.8e-05 
       LPnetlib/lp_agg3,  40,   11, 2.7e-04, 4.1e-01 
    LPnetlib/lp_bandm,  20,     0, 7.0e-09, 3.1e-07 
LPnetlib/lp_beaconfd,  10,     0, 6.5e-09, 4.9e-08 
      LPnetlib/lp_blend,  12,     0, 1.8e-10, 2.8e-09 
        LPnetlib/lp_bnl1,  63,     0, 2.8e-09, 2.8e-07

**Comment by echu** [comment]
There's another scaling routine you can try. I forget if it's just a
compile time flag. I'd be curious to see if it's the same thing or not.
It's also possible it doesn't get unscaled properly.

If it's not trivial for you to do, send me the test code (or post it to
github), and I can dig into it a bit.

Eric

**Comment by echu** [comment]
Oh, also, run the numbers after calling ECOS_cleanup. If I remember
correctly, unequilibration happens in the cleanup phase.

That might be the source of your confusion. We've talked about separating
the equilibration into two separate calls: ECOS_scale and ECOS_unscale.
Also, the scaling works by mutating the data then restoring it after
cleanup. So what you think is the A (G) matrix is in fact a scaled version
of it. At least, at the moment you use it.

We probably will change this interface and make a copy of the data to avoid
that kind of confusion.

But if this doesn't fix it, then there's definitely something to look at.

Eric

**Comment by tiagoakle** [comment]
Sure it's under ecos/test/matlab in the develop branch.
An error while unscaling can explain it, but that would affect all
problems. Another possibility is that some of the scaling factors are
enormous, and the effect is not as bad for socp problems because they get
averaged over the cone.

On Monday, January 19, 2015, Eric Chu <notifications@github.com> wrote:

> There's another scaling routine you can try. I forget if it's just a
> compile time flag. I'd be curious to see if it's the same thing or not.
> It's also possible it doesn't get unscaled properly.
>
> If it's not trivial for you to do, send me the test code (or post it to
> github), and I can dig into it a bit.
>
> Eric
> On Mon, Jan 19, 2015 at 10:14 AM tiagoakle <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
> > @mcg1969 <https://github.com/mcg1969> @adomahidi
> > <https://github.com/adomahidi>. I ran the following experiment:
> > Solved the first 10 standard form lps in LPnetlib with equilibration and
> > evaluate the residuals and complementarity. Then repeat without
> > equilibration.
> >
> > You will see that with equilibration, ecos in fact returns optimal for
> all
> > but the linear residuals for *all* problems are too large.
> >
> > On the other hand without equilibration ecos fails at 2 problems
> > but the ones it does solve, have more meaningful answers.
> >
> > Some part of the equilibration is broken, I'm afraid the tests don't
> > look at the residuals, and we've been measuring success mostly
> > by the number of problems correctly categorized as optimal, infeasible,
> > etc.
> >
> > Results:
> > //LP With Ruiz scaling
> > Problem name Iter Flag Norm Residual Complementarity
> > LPnetlib/lp_25fv47, 30, 0, 3.3e+03, 7.3e-06
> > LPnetlib/lp_adlittle, 13, 0, 1.4e+04, 5.0e-06
> > LPnetlib/lp_afiro, 9, 0, 9.8e+01, 1.1e-07
> > LPnetlib/lp_agg, 98, 0, 5.8e+05, 7.0e-06
> > LPnetlib/lp_agg2, 30, 0, 2.5e+05, 3.6e-06
> > LPnetlib/lp_agg3, 30, 0, 2.6e+05, 1.2e-05
> > LPnetlib/lp_bandm, 21, 0, 7.3e+02, 7.2e-08
> > LPnetlib/lp_beaconfd, 12, 0, 9.2e+04, 5.3e-08
> > LPnetlib/lp_blend, 12, 0, 7.8e+01, 7.6e-08
> > LPnetlib/lp_bnl1, 62, 0, 8.5e+02, 1.3e-06
> >
> > //LP Without Ruiz scaling
> > Problem name Iter Flag Norm Residual Complementarity
> > LPnetlib/lp_25fv47, 33, 0, 2.7e-08, 7.5e-08
> > LPnetlib/lp_adlittle, 12, 0, 3.2e-07, 9.0e-05
> > LPnetlib/lp_afiro, 9, 0, 4.6e-09, 5.6e-08
> > LPnetlib/lp_agg, 92, 0, 9.9e-09, 4.3e-06
> > LPnetlib/lp_agg2, 100, 10, 4.6e-06, 8.8e-05
> > LPnetlib/lp_agg3, 40, 11, 2.7e-04, 4.1e-01
> > LPnetlib/lp_bandm, 20, 0, 7.0e-09, 3.1e-07
> > LPnetlib/lp_beaconfd, 10, 0, 6.5e-09, 4.9e-08
> > LPnetlib/lp_blend, 12, 0, 1.8e-10, 2.8e-09
> > LPnetlib/lp_bnl1, 63, 0, 2.8e-09, 2.8e-07
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/embotech/ecos/issues/104#issuecomment-70537188>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/embotech/ecos/issues/104#issuecomment-70581071>.
>


-- 
Santiago Akle
+1 650 919 4833
tiagoakle@gmail.com

**Comment by tiagoakle** [comment]
I see I was not aware of that. However I'm calling from the matlab
interface. Does this mean the interface is either not unscaling or
modifying the underlying matlab matrix?
If so the bug is there.
I'll look into it later.

On Monday, January 19, 2015, Santiago Akle <tiagoakle@gmail.com> wrote:

> Sure it's under ecos/test/matlab in the develop branch.
> An error while unscaling can explain it, but that would affect all
> problems. Another possibility is that some of the scaling factors are
> enormous, and the effect is not as bad for socp problems because they get
> averaged over the cone.
>
> On Monday, January 19, 2015, Eric Chu <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
>> There's another scaling routine you can try. I forget if it's just a
>> compile time flag. I'd be curious to see if it's the same thing or not.
>> It's also possible it doesn't get unscaled properly.
>>
>> If it's not trivial for you to do, send me the test code (or post it to
>> github), and I can dig into it a bit.
>>
>> Eric
>> On Mon, Jan 19, 2015 at 10:14 AM tiagoakle <notifications@github.com>
>> wrote:
>>
>> > @mcg1969 <https://github.com/mcg1969> @adomahidi
>> > <https://github.com/adomahidi>. I ran the following experiment:
>> > Solved the first 10 standard form lps in LPnetlib with equilibration
>> and
>> > evaluate the residuals and complementarity. Then repeat without
>> > equilibration.
>> >
>> > You will see that with equilibration, ecos in fact returns optimal for
>> all
>> > but the linear residuals for *all* problems are too large.
>> >
>> > On the other hand without equilibration ecos fails at 2 problems
>> > but the ones it does solve, have more meaningful answers.
>> >
>> > Some part of the equilibration is broken, I'm afraid the tests don't
>> > look at the residuals, and we've been measuring success mostly
>> > by the number of problems correctly categorized as optimal, infeasible,
>> > etc.
>> >
>> > Results:
>> > //LP With Ruiz scaling
>> > Problem name Iter Flag Norm Residual Complementarity
>> > LPnetlib/lp_25fv47, 30, 0, 3.3e+03, 7.3e-06
>> > LPnetlib/lp_adlittle, 13, 0, 1.4e+04, 5.0e-06
>> > LPnetlib/lp_afiro, 9, 0, 9.8e+01, 1.1e-07
>> > LPnetlib/lp_agg, 98, 0, 5.8e+05, 7.0e-06
>> > LPnetlib/lp_agg2, 30, 0, 2.5e+05, 3.6e-06
>> > LPnetlib/lp_agg3, 30, 0, 2.6e+05, 1.2e-05
>> > LPnetlib/lp_bandm, 21, 0, 7.3e+02, 7.2e-08
>> > LPnetlib/lp_beaconfd, 12, 0, 9.2e+04, 5.3e-08
>> > LPnetlib/lp_blend, 12, 0, 7.8e+01, 7.6e-08
>> > LPnetlib/lp_bnl1, 62, 0, 8.5e+02, 1.3e-06
>> >
>> > //LP Without Ruiz scaling
>> > Problem name Iter Flag Norm Residual Complementarity
>> > LPnetlib/lp_25fv47, 33, 0, 2.7e-08, 7.5e-08
>> > LPnetlib/lp_adlittle, 12, 0, 3.2e-07, 9.0e-05
>> > LPnetlib/lp_afiro, 9, 0, 4.6e-09, 5.6e-08
>> > LPnetlib/lp_agg, 92, 0, 9.9e-09, 4.3e-06
>> > LPnetlib/lp_agg2, 100, 10, 4.6e-06, 8.8e-05
>> > LPnetlib/lp_agg3, 40, 11, 2.7e-04, 4.1e-01
>> > LPnetlib/lp_bandm, 20, 0, 7.0e-09, 3.1e-07
>> > LPnetlib/lp_beaconfd, 10, 0, 6.5e-09, 4.9e-08
>> > LPnetlib/lp_blend, 12, 0, 1.8e-10, 2.8e-09
>> > LPnetlib/lp_bnl1, 63, 0, 2.8e-09, 2.8e-07
>> >
>> > —
>> > Reply to this email directly or view it on GitHub
>> > <https://github.com/embotech/ecos/issues/104#issuecomment-70537188>.
>> >
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/embotech/ecos/issues/104#issuecomment-70581071>.
>>
>
>
> --
> Santiago Akle
> +1 650 919 4833
> tiagoakle@gmail.com <javascript:_e(%7B%7D,'cvml','tiagoakle@gmail.com');>
>


-- 
Santiago Akle
+1 650 919 4833
tiagoakle@gmail.com

**Comment by tiagoakle** [comment]
There were two culprits ECOS failed to unscale c correctly and returned the wrong "s":

The method in charge of removing the scaling was rescaling  "s" instead of unscaling, the resulting 
"s" was mostly good if the Gequil vector was close to one. Otherwise the results were bogus. 

The scaling of c was removed *twice* once in the backscale method and 
once in the ECOS_cleanup method. This would modify the underlying MATLAB structure and 
change the result in MATLAB.
