### ISSUE TITLE
Nondeterminism in ECOS BB

### ISSUE THREAD

**Issue by SteveDiamond** [embotech/ecos#106]
cvxpy users are getting nondeterministic results for the problem
```
from cvxpy import *
x = IntVar()
cost = square(x - 0.2)
prob = Problem(Minimize(cost))
prob.solve()
```
which calls ECOS BB. It's quite possible the nondeterminism is in cvxpy. I'm investigating that possibility right now. But I'm posting this too in case there is non-determinism in ECOS BB itself.

**Comment by SteveDiamond** [comment]
I'm quite sure now that the input from cvxpy is deterministic. So something nondeterministic is happening in ECOS or ECOS BB. This is an important issue because it's causing cvxpy unit tests to fail for some people.

**Comment by hanwang** [comment]
Fixed with the latest patch.
