### ISSUE TITLE
BB int variable

### ISSUE THREAD

**Issue by borient** [embotech/ecos#108]
According to the description, int_vars_idx is an array with indices of integer variables (0-based indexing, must be strictly monotonically increasing).
However, the line below (line 93 in ecos_bb_preproc.c) shows that the index starts right after the end of the binary index.

 /* Now insert the new zeros and expand the column indices as needed for INTEGER vars*/
    for (j=num_bool_vars; j<(num_bool_vars + num_int_vars); ++j){
        k = int_vars_idx[j];

**Comment by hanwang** [comment]
Thank you, good catch, fixed with latest commit.
