### ISSUE TITLE
Unbounded status returned for infeasible problem

### ISSUE THREAD

**Issue by IainNZ** [embotech/ecos#109]
Detected in ECOS 1.05, might be resolved but can't easily build right now:

```
Original problem:

Max   x
s.t.  x = 3
      8u + 9v <= 25
      -x + u + v = 0
      x free
      u <= 0
      v >= 0


ECOS form:

Min  -x
s.t.  x           == 3
     -x +  u +  v == 0
          8u + 9v <= 25
           u      <= 0
               -v <= 0

ECOS data:

n = 3
m = 3
p = 2
l = 3
ncones = 0
q = Int[]
G = [ 0  8  9;
      0  1  0;
      0  0 -1]
A = [ 1  0  0;
     -1  1  1]
c = [-1, 0, 0]
h = [25, 0, 0]
b = [ 3, 0]
```

```
ECOS 1.0.5 - (c) A. Domahidi, ETH Zurich & embotech 2012-14. Support: ecos@embotech.com

It     pcost         dcost      gap     pres    dres     k/t     mu      step     IR
 0   -3.000e+00   -1.133e+01   +1e+01   9e-01   2e+00   1e+00   3e+00    N/A     3 1 -
 1   -3.000e+00   -4.309e+00   +2e+00   2e-01   3e-01   3e-01   5e-01   0.8642   2 3 3
 2   -3.000e+00   +8.743e+00   +3e-01   3e+00   6e+00   4e+01   9e-02   0.9400   4 4 4
 3   -3.000e+00   +3.614e+03   +4e-03   3e+00   6e+00   4e+03   1e-03   0.9886   4 4 4
 4   -3.000e+00   +2.873e+05   +4e-05   2e+00   5e+00   3e+05   1e-05   0.9899   5 5 5
 5   -2.998e+00   +2.380e+07   +4e-07   2e+00   4e+00   2e+07   1e-07   0.9899   1 1 1

UNBOUNDED (within feastol=3.7e-08).
Runtime: 0.000112 seconds.
```

**Comment by IainNZ** [comment]
https://github.com/JuliaOpt/ECOS.jl/pull/17

**Comment by adomahidi** [comment]
Confirmed to happen also with version 1.1.1

**Comment by echu** [comment]
Hmm. I can't duplicate this error (at least, not in CVXPY). @adomahidi, how are you testing this problem?

**Comment by IainNZ** [comment]
@echu I have a feeling it is somewhat sensitive to the exact formulation, can you dump the data structures passed to ECOS from CVXPY?

**Comment by echu** [comment]
Here's CVXPY's output, as reported by `get_problem_data` (with some formatting).
```
n = 3
m = 3
p = 2
l = 3
q = []
G = [[ 0.  8.  9.]
     [ 0.  1.  0.]
     [ 0.  0. -1.]]
A = [[ 1.  0.  0.]
     [-1.  1.  1.]]
c = [-1.  0.  0.]
h = [ 25.  -0.  -0.]
b = [ 3. -0.]
```
Here's the verbose solver dump:
```
ECOS 1.1.1 - (c) A. Domahidi, ETH Zurich & embotech 2012-15. Support: ecos@embotech.com

It     pcost         dcost      gap     pres    dres     k/t     mu      step     IR
 0   -3.000e+00   -1.133e+01   +1e+01   9e-01   2e+00   1e+00   3e+00    N/A     1 1 -
 1   -3.000e+00   -4.309e+00   +2e+00   2e-01   3e-01   3e-01   5e-01   0.8642   1 1 1
 2   -3.000e+00   +8.743e+00   +3e-01   3e+00   6e+00   4e+01   9e-02   0.9400   1 1 1
 3   -3.000e+00   +3.614e+03   +4e-03   3e+00   6e+00   4e+03   1e-03   0.9886   1 1 1
 4   -2.999e+00   +2.685e+05   +4e-05   2e+00   5e+00   3e+05   1e-05   0.9890   1 1 1
 5   -2.999e+00   +2.067e+07   +5e-07   2e+00   4e+00   2e+07   1e-07   0.9890   1 0 0
 6   -2.995e+00   +1.634e+09   +5e-09   2e+00   4e+00   2e+09   1e-09   0.9890   2 0 0

PRIMAL INFEASIBLE (within feastol=2.3e-09).
Runtime: 0.000076 seconds.
```

@adomahidi claims its still broken, so maybe he can shed some light?

**Comment by IainNZ** [comment]
Interesting, hopefully it is fixed then. Unless its sensitive to the signs on the zeros, that'd be an awkward one :D

**Comment by adomahidi** [comment]
I thought I had the same problem with 1.1.1 - rerunning it now seems to work. Maybe I was calling the wrong ECOS build. Sorry about that.

**Comment by IainNZ** [comment]
Great, I'll try to upgrade!

**Comment by echu** [comment]
In any case, I'm happy we got another test case out of this. :)

**Comment by IainNZ** [comment]
I'm not sure if you are aware of this, but the Julia packages JuMP and Convex are sort of an exterior test set for ECOS too. I'm not 100% sure about Convex, but JuMP has a lot of tests that require a solver and it runs those test with every solver we have wrapped. If ECOS was in disagreement, we'd find it quickly. Thats how I found this case (although its been fixed), because only ECOS was failing a test in JuMPeR.jl. I like to think the collective test pool does a pretty good job of covering ECOS. Will be good if we get around to wrapping the B&B functionality, that'd let us run even more tests with it.

**Comment by mcg1969** [comment]
That makes sense. I have found many a bug in SDPT3, SeDuMi, even MOSEK and Gurobi using CVX.



On Mar 1, 2015, at 2:09 PM, Iain Dunning <notifications@github.com<mailto:notifications@github.com>> wrote:


I'm not sure if you are aware of this, but the Julia packages JuMP and Convex are sort of an exterior test set for ECOS too. I'm not 100% sure about Convex, but JuMP has a lot of tests that require a solver and it runs those test with every solver we have wrapped. If ECOS was in disagreement, we'd find it quickly. Thats how I found this case (although its been fixed), because only ECOS was failing a test in JuMPeR.jl. I like to think the collective test pool does a pretty good job of covering ECOS. Will be good if we get around to wrapping the B&B functionality, that'd let us run even more tests with it.

**Comment by echu** [comment]
That's good to know!

I wonder if it isn't too hard to set up Travis to run the cvxpy and jump
tests whenever we make changes... That would probably give us a good idea
if we break anything downstream.

**Comment by IainNZ** [comment]
Certainly easy enough for JuMP, would be happy to help with that.

**Comment by tkelman** [comment]
Not very hard. Patch this line https://github.com/JuliaOpt/ECOS.jl/blob/6f2c70d88d38e7fb7b88a994f2755d71917c236d/deps/build.jl#L15 to point to whatever you want to test.

Note that recent versions of ECOS segfault on 64-bit Windows, see https://github.com/JuliaOpt/ECOS.jl/issues/16#issuecomment-72537761 - no change on the latest develop branch. I'd put a little more effort into running things on AppVeyor (or hell, cross-compile from Linux and run it in Wine - same segfault there, though using a build system more capable than hand-written makefiles would make that much simpler) to make sure the core C library runs correctly on all platforms, and not just within the confines of Python or Matlab.

**Comment by echu** [comment]
I've got an appveyor test for the Python module. It *seems* to build and
run fine there (the tests don't exercise all of ECOS, so it's possible the
segfault occurs on some untouched code path), but I haven't built the C
library standalone.

Looks like there's still some work to be done to iron that out. Thanks for
pointing it out!
