### ISSUE TITLE
Wrong objective values in info-structure for linear program on Linux

### ISSUE THREAD

**Issue by AndreasHempel** [embotech/ecos#118]
The relevant problem data (Matlab-savefile) can be found [here](https://www.dropbox.com/s/9y94daeeec54b7n/ecos_fail.mat?dl=0).
Calling code is:
`[x,~,info] = ecos(c,G,h,cones); c'*x - info.pcost`

When solving the (small) LP above with ECOS 1.1.1 in Matlab R2014a on Linux, the reported objective function values (per iteration and in the return info-structure) do not match `c'*x`, i.e. the cost function evaluated at the returned optimizer. The difference is on the order of 1e-1. Subsequent identical calls will generate different outputs and `c'x - info.pcost` will continuously decrease.

When solving the same problem in Matlab 2014b on Mac OS X, this issue does not occur: `c'x - info.pcost` is numerically zero. 

The optimizers that are returned on Linux and Mac match, so the problem seems to be in the evaluation of the cost function and not in the actual solution of the problem.

**Comment by adomahidi** [comment]
I believe this has been fixed in version 2.0.0 - just ran this under linux 64 bit and it worked. @AndreasHempel Can you confirm?

**Comment by AndreasHempel** [comment]
Just tested this again with ECOS 2.0.1. Can confirm, the issues seems to be fixed.
