### ISSUE TITLE
Need to update the ECOS on pip

### ISSUE THREAD

**Issue by SteveDiamond** [embotech/ecos#119]
This commit fixes an important issue in the cvxpy-ECOS BB interface:

embotech/ecos@bde8662

I don't think it's in the ECOS on pip. Could you put out a new version on pip that has this commit? I posted an issue on ecos-python, but I'm posting it here too because you may need to bump the ECOS version number.

**Comment by echu** [comment]
We just did this: https://pypi.python.org/pypi/ecos/2.0.0
