### ISSUE TITLE
warm start for mixed integer socp

### ISSUE THREAD

**Issue by chenhappy** [embotech/ecos#140]
is there a way to warm start the mixed integer (branch and bound) part of the codes? for my problems that only has boolean constraints I am able to provide initial guess for the Boolean variables, which I believe should help to tighten the bound quickly and speed up the search by NOT exploring many branches.

**Comment by hanwang** [comment]
There's no explicit current support for a warm start for as that would require the underlying solver to take an initial guess.

However, you can include a linear term in the obj for +- epsilon where epsilon is positive for booleans you want to be 1 and - for booleans you want to be 0 to attempt to "guide" the solution to a viable first solution for pruning. 

Your mileage will vary on the above trick as I've seen dramatic speedups and no effects from "guiding" the solution as described above.
