### ISSUE TITLE
Installation guide linux(Ubuntu)

### ISSUE THREAD

**Issue by jsroyal** [embotech/ecos#151]
I'm facing problem to how to install ECOS my system. Is there anybody to help me.
I clone ecos repo my system after that how to install in ubuntu there not any readme for that and also search on google not finding any source to install.
This is system details.
![image](https://cloud.githubusercontent.com/assets/10773353/23756314/48aabcfe-0509-11e7-86c3-0f5b5859466d.png)

**Comment by adomahidi** [comment]
Python: `pip install ecos`
Matlab: download binaries from www.embotech.com/ECOS/Download

and see also www.embotech.com/ECOS/Install

**Comment by jsroyal** [comment]
@adomahidi Thank you for reply.
install ECOS source code (C API only)
I want to install only for c.
Is that necessary to install Matlab for ecos?
I gone through guide not getting clear idea so please help.

**Comment by jsroyal** [comment]
Got this link also but how it work did not find please help.
[Link](https://www.embotech.com/ECOS/How-to-use/C-API)
There is two example but did not get where to start and how to ecos.

**Comment by jsroyal** [comment]
Hey! Can you please help me?
Still stuck here won't able use.
Can I get related resources of it.
