### ISSUE TITLE
ECOS_setup implementation missing?

### ISSUE THREAD

**Issue by imkaywu** [embotech/ecos#162]
I might be incorrect, but I couldn't seem to find the ECOS_setup implementation?

**Comment by echu** [comment]
Could you elaborate a little? What did you try to do and what was the error
message?

**Comment by imkaywu** [comment]
I tried to initialize the solver using ECOS_setup, but I couldn't find the implementation of ECOS_setup in ecos.c. I used this method anyway, and tried to print out the content of matrix G, but the data it points to is incorrect, and I got a memory access violation error. Since we need to allocate space for pwork, I was just wondering how is memory allocated for this data structure?
