### ISSUE TITLE
CBF file reader

### ISSUE THREAD

**Issue by erling-d-andersen** [embotech/ecos#180]
We can provide source code that will build a binary that can read CBF files and run ECOS if you are interested.

CBF is the standard format of

cblib.zib.de

**Comment by adomahidi** [comment]
That would be very interesting, Erling. Could this be integrated into Travis CI? Does it work under linux?

**Comment by erling-d-andersen** [comment]
It is just a few simple ANSI C files that builds into simple binary that can read CBF files. That is all. We build and run it on Linux.

I suppose you can integrate it into Travis but I do not know Travis. In any case we will not do that.

**Comment by erling-d-andersen** [comment]
The binary send sends the problem into ecos and lets it solve it.

**Comment by erling-d-andersen** [comment]
[ecos_cli.tar.gz](https://github.com/embotech/ecos/files/3492067/ecos_cli.tar.gz)

<pre>
build with:
$ make -f Makefile.cbf runecoscbf

run with
$ ./runecoscbf cbfprob.cbf[.gz]

for example
$ ./runecoscbf /remote/mosek/testprob/public/cblib/instances/cbf/co/cbl_bss1.cbf.gz

</pre>

**Comment by adomahidi** [comment]
That's great Erling, thanks a lot for providing this!

**Comment by erling-d-andersen** [comment]
Note this interface does support all features of CBF format such RQUAD cones since ecos does not support that. Also no integer variables are handled.

Anyone who wants those features can most likely easily extend the interface.
