### ISSUE TITLE
ECOS MbedTLS

### ISSUE THREAD

**Issue by xeno91** [embotech/ecos#182]
I am trying to include the mbedTLS library into my eCos Project. According to the eCosPro Reference Manual (https://doc.ecoscentric.com/ref/mbedtls-overview.html) there should be a package for mbedTLS (CYGPKG_MBEDTLS) but I can't find this package anywehere.
There are changes need to be made to the following files of the mbedTLS library: src/platform.c, include/platform.h and include/config.h.
I assume it is a implementation of a hardware entropy collector.

Does anyone know how to enable mbedTLS on eCos or can provide me the package?

**Comment by adomahidi** [comment]
I think this is not the project you intend to post to?
