### ISSUE TITLE
error: "_TWO_DIGIT_EXPONENT' undeclared

### ISSUE THREAD

**Issue by mllima** [embotech/ecos#46]
I could not install ecos on Python 3.3, windows 7, due to the error described above in function ECOS_solve of ecos.c. Cold you, please, help me on it?

**Comment by echu** [comment]
[Appveyor](https://ci.appveyor.com/project/echu/ecos-python) tests show successful Windows installation via [miniconda](http://conda.pydata.org/miniconda.html).

**Comment by rmcgibbo** [comment]
I'm seeing the same thing on py35 (Visual Studio 2015) with ecos-2.0.4.

**Comment by jcrichard** [comment]
Hey. Error is still there. I comment the line and it works.

**Comment by joseortiz3** [comment]
This error is still there.

**Comment by echu** [comment]
A lot of these threads about installation issues seem related to visual
studio deprecating their support for the exponent format. Let’s see if I
have some time this evening to get it right (difficult to do without a
Windows machine, but still possible).

Thanks for putting up with this.

Relevant (for my sake):
https://msdn.microsoft.com/en-us/library/0fatw238.aspx
