### ISSUE TITLE
ecos crashes MATLAB on purely linear program

### ISSUE THREAD

**Issue by MatthiasKauer** [embotech/ecos#49]
Hi,
I managed to crash my MATLAB instance when I select ecos for the following basic linear program. It runs fine with cvx' basic solver (sdpt3 on my machine), i.e., with cvx_solver ecos commented out. 

Can you confirm this or help me debug on my side?
Am I missing anything or is there a problem with purely linear programs?

Best,
Matthias 

```
clear all;
%http://people.brunel.ac.uk/~mastjjb/jeb/or/morelp.html
n = 2; c = [1; 1]; A = [50, 24; 30, 33]; b = [40*60; 35*60];

cvx_begin
    cvx_solver ecos
    variables x(n);

    maximize (c' * x);
    subject to
        x >= [45; 5];
        A*x <= b;
cvx_end
x
%correct: x = [45, 6.25]
```

**Comment by manajalali** [comment]
I have the same problem. 
ECOS works when using with cvx, but crashes when using a mex file. 
How did you eventually solve the problem?

**Comment by MatthiasKauer** [comment]
I haven't worked with MATLAB in a while. I'm afraid I don't recall what I did here. After 4 years, you're most likely seeing an entirely different issue anyway.

**Comment by echu** [comment]
@manajalali , is it a segfault you’re getting? I no longer have access to Matlab, so maybe this is something @adomahidi has to help with.

**Comment by manajalali** [comment]
I think it should be a segfault. This is the error it is giving me and I have seen in forums that people encountered this problem while running mex files.
         Access violation detected at Mon Jul 09 09:07:08 2018 -0400
--------------------------------------------------------------------------------

Configuration:
  Crash Decoding           : Disabled - No sandbox or build area path
  Crash Mode               : continue (default)
  Default Encoding         : windows-1252
  Deployed                 : false
  Graphics Driver          : Unknown hardware 
  Graphics card 1          : NVIDIA ( 0x10de ) NVIDIA GeForce 940MX Version 22.21.13.8264 (2017-6-18)
  Graphics card 2          : Intel Corporation ( 0x8086 ) Intel(R) HD Graphics 520 Version 21.20.16.4550 (2016-11-11)
  Java Version             : Java 1.8.0_144-b01 with Oracle Corporation Java HotSpot(TM) 64-Bit Server VM mixed mode
  MATLAB Architecture      : win64
  MATLAB Entitlement ID    : 6257193
  MATLAB Root              : E:\matlab2018
  MATLAB Version           : 9.4.0 (R2018a)
  OpenGL                   : hardware
  Operating System         : Microsoft Windows 10 Enterprise
  Process ID               : 11504
  Processor ID             : x86 Family 6 Model 78 Stepping 3, GenuineIntel
  Session Key              : 78c78248-ce61-425a-af1b-0a5f7ffe8eab
  Window System            : Version 10.0 (Build 16299)

Fault Count: 1


Abnormal termination

Register State (from fault):
  RAX = 0000000000000000  RBX = 0000000000000005
  RCX = 0000000000000000  RDX = 0000000000000000
  RSP = 00000000043f9120  RBP = 00000000043f9250
  RSI = 0000000000000000  RDI = 000000003fa0c090
 
   R8 = 0000000000000880   R9 = 0000000000000000
  R10 = 00000000ffffffff  R11 = 0000000000000000
  R12 = 0000000000000000  R13 = 0000000000000000
  R14 = 00000000043f95d0  R15 = 0000000000000000
 
  RIP = 00007ffb928df258  EFL = 00010202
 
   CS = 0033   FS = 0053   GS = 002b

Stack Trace (from fault):
[  0] 0x00007ffb928df258      E:\matlab2018\bin\ecos-matlab\bin\ecos.mexw64+00062040 mexFunction+00002712
[  1] 0x00000000fc626594                               bin\win64\libmex.dll+00288148 MexRetrieveVersion+00002916
[  2] 0x00000000fc62678c                               bin\win64\libmex.dll+00288652 MexRetrieveVersion+00003420
[  3] 0x00000000fc6268de                               bin\win64\libmex.dll+00288990 MexRetrieveVersion+00003758
[  4] 0x00000000fc612ec3                               bin\win64\libmex.dll+00208579 mexUnlock_800+00024147
[  5] 0x000000001c60c51a                     bin\win64\pgo\m_dispatcher.dll+00050458 Mfh_file::dispatch_fh_impl+00001114
[  6] 0x000000001c60c0b2                     bin\win64\pgo\m_dispatcher.dll+00049330 Mfh_file::dispatch_fh+00000062
[  7] 0x000000001c604674                     bin\win64\pgo\m_dispatcher.dll+00018036 Mfunction_handle::dispatch+00000420
[  8] 0x000000001d4e0189                            bin\win64\pgo\m_lxe.dll+00393609
[  9] 0x000000001d56a808                            bin\win64\pgo\m_lxe.dll+00960520 mwboost::serialization::singleton<mwboost::archive::detail::pointer_iserializer<mwboost::archive::binaryTerm_iarchive,ir::IrTree> >::get_instance+00121832
[ 10] 0x000000001d56b403                            bin\win64\pgo\m_lxe.dll+00963587 mwboost::serialization::singleton<mwboost::archive::detail::pointer_iserializer<mwboost::archive::binaryTerm_iarchive,ir::IrTree> >::get_instance+00124899
[ 11] 0x000000001d56c836                            bin\win64\pgo\m_lxe.dll+00968758 mwboost::serialization::singleton<mwboost::archive::detail::pointer_iserializer<mwboost::archive::binaryTerm_iarchive,ir::IrTree> >::get_instance+00130070
[ 12] 0x000000001d56d3f0                            bin\win64\pgo\m_lxe.dll+00971760 mwboost::serialization::singleton<mwboost::archive::detail::pointer_iserializer<mwboost::archive::binaryTerm_iarchive,ir::IrTree> >::get_instance+00133072
[ 13] 0x000000001d56c97f                            bin\win64\pgo\m_lxe.dll+00969087 mwboost::serialization::singleton<mwboost::archive::detail::pointer_iserializer<mwboost::archive::binaryTerm_iarchive,ir::IrTree> >::get_instance+00130399
[ 14] 0x000000001d56ca7e                            bin\win64\pgo\m_lxe.dll+00969342 mwboost::serialization::singleton<mwboost::archive::detail::pointer_iserializer<mwboost::archive::binaryTerm_iarchive,ir::IrTree> >::get_instance+00130654
[ 15] 0x000000001d4ee8a5                            bin\win64\pgo\m_lxe.dll+00452773
[ 16] 0x000000001d4eb335                            bin\win64\pgo\m_lxe.dll+00439093
[ 17] 0x000000001d4ea82e                            bin\win64\pgo\m_lxe.dll+00436270
[ 18] 0x000000001d4e8b35                            bin\win64\pgo\m_lxe.dll+00428853
[ 19] 0x000000001d4e8e9e                            bin\win64\pgo\m_lxe.dll+00429726
[ 20] 0x000000001d4e8e29                            bin\win64\pgo\m_lxe.dll+00429609
[ 21] 0x000000001c60c51a                     bin\win64\pgo\m_dispatcher.dll+00050458 Mfh_file::dispatch_fh_impl+00001114
[ 22] 0x000000001c60c0b2                     bin\win64\pgo\m_dispatcher.dll+00049330 Mfh_file::dispatch_fh+00000062
[ 23] 0x000000001c604674                     bin\win64\pgo\m_dispatcher.dll+00018036 Mfunction_handle::dispatch+00000420
[ 24] 0x000000001d4e2aa1                            bin\win64\pgo\m_lxe.dll+00404129
[ 25] 0x000000001d568e25                            bin\win64\pgo\m_lxe.dll+00953893 mwboost::serialization::singleton<mwboost::archive::detail::pointer_iserializer<mwboost::archive::binaryTerm_iarchive,ir::IrTree> >::get_instance+00115205
[ 26] 0x000000001d56a808                            bin\win64\pgo\m_lxe.dll+00960520 mwboost::serialization::singleton<mwboost::archive::detail::pointer_iserializer<mwboost::archive::binaryTerm_iarchive,ir::IrTree> >::get_instance+00121832
[ 27] 0x000000001d56b403                            bin\win64\pgo\m_lxe.dll+00963587 mwboost::serialization::singleton<mwboost::archive::detail::pointer_iserializer<mwboost::archive::binaryTerm_iarchive,ir::IrTree> >::get_instance+00124899
[ 28] 0x000000001d56c836                            bin\win64\pgo\m_lxe.dll+00968758 mwboost::serialization::singleton<mwboost::archive::detail::pointer_iserializer<mwboost::archive::binaryTerm_iarchive,ir::IrTree> >::get_instance+00130070
[ 29] 0x000000001d56d3f0                            bin\win64\pgo\m_lxe.dll+00971760 mwboost::serialization::singleton<mwboost::archive::detail::pointer_iserializer<mwboost::archive::binaryTerm_iarchive,ir::IrTree> >::get_instance+00133072
[ 30] 0x000000001d56c97f                            bin\win64\pgo\m_lxe.dll+00969087 mwboost::serialization::singleton<mwboost::archive::detail::pointer_iserializer<mwboost::archive::binaryTerm_iarchive,ir::IrTree> >::get_instance+00130399
[ 31] 0x000000001d56ca7e                            bin\win64\pgo\m_lxe.dll+00969342 mwboost::serialization::singleton<mwboost::archive::detail::pointer_iserializer<mwboost::archive::binaryTerm_iarchive,ir::IrTree> >::get_instance+00130654
[ 32] 0x000000001d4ee8a5                            bin\win64\pgo\m_lxe.dll+00452773
[ 33] 0x000000001d4eb335                            bin\win64\pgo\m_lxe.dll+00439093
[ 34] 0x000000001d4ea82e                            bin\win64\pgo\m_lxe.dll+00436270
[ 35] 0x000000001d4f1b9a                            bin\win64\pgo\m_lxe.dll+00465818
[ 36] 0x000000001d4f133d                            bin\win64\pgo\m_lxe.dll+00463677
[ 37] 0x000000001d4f144e                            bin\win64\pgo\m_lxe.dll+00463950
[ 38] 0x000000001d691d9c                            bin\win64\pgo\m_lxe.dll+02170268 mwboost::serialization::singleton<mwboost::archive::detail::pointer_oserializer<mwboost::archive::binary_oarchive,MathWorks::lxe::PreLineExecutionEvent> >::get_instance+00475644
[ 39] 0x000000001d691d4a                            bin\win64\pgo\m_lxe.dll+02170186 mwboost::serialization::singleton<mwboost::archive::detail::pointer_oserializer<mwboost::archive::binary_oarchive,MathWorks::lxe::PreLineExecutionEvent> >::get_instance+00475562
[ 40] 0x000000001d4c051d                            bin\win64\pgo\m_lxe.dll+00263453
[ 41] 0x000000001c818acf                    bin\win64\pgo\m_interpreter.dll+00297679 inEvalCmdWithLocalReturn+00000063
[ 42] 0x00000000fb60bedb                          bin\win64\libmwbridge.dll+00114395 mnParser+00001595
[ 43] 0x000000001c456564                                  bin\win64\mcr.dll+00222564 mcr::runtime::setInterpreterThreadSingletonToCurrent+00091332
[ 44] 0x000000001c4597ae                                  bin\win64\mcr.dll+00235438 mcr::runtime::setInterpreterThreadSingletonToCurrent+00104206
[ 45] 0x000000001c476c8a                                  bin\win64\mcr.dll+00355466 mcrRegisterExternalFunction+00007930
[ 46] 0x000000001c4789bc                                  bin\win64\mcr.dll+00362940 mcrRegisterExternalFunction+00015404
[ 47] 0x000000001c475bff                                  bin\win64\mcr.dll+00351231 mcrRegisterExternalFunction+00003695
[ 48] 0x000000001c476c46                                  bin\win64\mcr.dll+00355398 mcrRegisterExternalFunction+00007862
[ 49] 0x000000001c475ce3                                  bin\win64\mcr.dll+00351459 mcrRegisterExternalFunction+00003923
[ 50] 0x000000001c478ff6                                  bin\win64\mcr.dll+00364534 mcrRegisterExternalFunction+00016998
[ 51] 0x00000000fd014f67                                  bin\win64\iqm.dll+00544615 iqm::IqmPlugin<cmddistributor::PackagedTaskIIP>::getIIP+00016215
[ 52] 0x00000000fd01567f                                  bin\win64\iqm.dll+00546431 iqm::PackagedTaskPlugin::execute+00000911
[ 53] 0x00000000fd014fed                                  bin\win64\iqm.dll+00544749 iqm::IqmPlugin<cmddistributor::PackagedTaskIIP>::getIIP+00016349
[ 54] 0x00000000fd0154c3                                  bin\win64\iqm.dll+00545987 iqm::PackagedTaskPlugin::execute+00000467
[ 55] 0x00000000fcfed9ea                                  bin\win64\iqm.dll+00383466 iqm::Iqm::setupIqmFcnPtrs+00071994
[ 56] 0x00000000fcfed84c                                  bin\win64\iqm.dll+00383052 iqm::Iqm::setupIqmFcnPtrs+00071580
[ 57] 0x00000000fcfce722                                  bin\win64\iqm.dll+00255778 iqm::Iqm::deliver+00003730
[ 58] 0x00000000fcfcf749                                  bin\win64\iqm.dll+00259913 iqm::Iqm::deliver+00007865
[ 59] 0x00000001001aa211                        bin\win64\libmwservices.dll+01810961 services::system_events::PpeDispatchHook::dispatchOne+00030865
[ 60] 0x00000001001b7ff3                        bin\win64\libmwservices.dll+01867763 sysq::addProcessPendingEventsUnitTestHook+00004659
[ 61] 0x00000001001b81e0                        bin\win64\libmwservices.dll+01868256 sysq::addProcessPendingEventsUnitTestHook+00005152
[ 62] 0x00000001001b9576                        bin\win64\libmwservices.dll+01873270 sysq::getCondition+00003446
[ 63] 0x00000001001bb0e6                        bin\win64\libmwservices.dll+01880294 svWS_ProcessPendingEvents+00000230
[ 64] 0x000000001c460737                                  bin\win64\mcr.dll+00263991 mcr::runtime::setInterpreterThreadSingletonToCurrent+00132759
[ 65] 0x000000001c462360                                  bin\win64\mcr.dll+00271200 mcr::runtime::setInterpreterThreadSingletonToCurrent+00139968
[ 66] 0x000000001c43e9b7                                  bin\win64\mcr.dll+00125367 mcr_process_events+00001959
[ 67] 0x000000001c30fef5                             bin\win64\MVMLocal.dll+00327413 mvm_server::inproc::LocalFactory::terminate+00139589
[ 68] 0x00000000fa9605b9                                  bin\win64\mvm.dll+01246649 mvm::detail::initLocalMvmHack+00000793
[ 69] 0x00000000fa960dcb                                  bin\win64\mvm.dll+01248715 mvm::detail::SessionImpl::privateSession+00000555
[ 70] 0x00000000fa960ff1                                  bin\win64\mvm.dll+01249265 mvm::detail::SessionImpl::privateSession+00001105
[ 71] 0x000000014000780d                               bin\win64\MATLAB.exe+00030733
[ 72] 0x000000014000862f                               bin\win64\MATLAB.exe+00034351
[ 73] 0x00007ffb9b7c1fe4                   C:\WINDOWS\System32\KERNEL32.DLL+00073700 BaseThreadInitThunk+00000020
[ 74] 0x00007ffb9e2dcb31                      C:\WINDOWS\SYSTEM32\ntdll.dll+00445233 RtlUserThreadStart+00000033


This error was detected while a MEX-file was running. If the MEX-file
is not an official MathWorks function, please examine its source code
for errors. Please consult the External Interfaces Guide for information
on debugging MEX-files.
