### ISSUE TITLE
possible numerical issue

### ISSUE THREAD

**Issue by jaehyunp** [embotech/ecos#70]
Some of the students in the convex optimization class were having an issue with problem A3.19, in which none of the cvxpy solvers was stable. I have this code, which is the literal translation of the matlab solution we have. On my machine (Windows x64, ecos 1.0.4, cvxpy 0.2.6, numpy 1.8.1, scipy 0.14.0), this code gives the expected answer (5077.5), but when the lines marked with ### were swapped, it gives a solver_error with optimal value of None. Steven suggested I post this issue here. Thanks for the help!

```python
# exercise A3.19
import numpy as np
import cvxpy as cvx

# data
a = [0.5, -0.5, 0.2, -0.7, 0.6, -0.2, 0.7, -0.5, 0.8, -0.4]
l = [40, 20, 40, 40, 20, 40, 30, 40, 30, 60]
Preq = np.arange(a[0], a[0]*(l[0]+0.5), a[0])
for i in range(1, len(l)):
    Preq=np.r_[ Preq, np.arange(Preq[-1]+a[i], Preq[-1]+a[i]*(l[i]+0.5), a[i]) ]
Preq = np.asmatrix(Preq).T
T = sum(l)
Peng_max = 20.0
Pmg_min = -6.0
Pmg_max = 6.0
Ebatt_max = 100.0
eta = 0.1
gamma = 0.1

# solve
Peng = cvx.Variable(T)
Pmg = cvx.Variable(T)
Pbr = cvx.Variable(T)
E = cvx.Variable(T+1)

obj = cvx.Minimize(cvx.sum_entries(Peng) + \
          gamma * cvx.sum_squares(Peng) + \
          1e-5 * cvx.sum_entries(cvx.neg(Pmg)))
cons = [Preq == Peng + Pmg - Pbr, 
        E[0] == E[T],
        Pmg_min <= Pmg, Pmg <= Pmg_max,        ###
        Pbr >= 0, 0 <= Peng, Peng <= Peng_max, ###
        0 <= E, E <= Ebatt_max]

for t in range(T):
    cons += [E[t+1] <= E[t]-Pmg[t]-eta*cvx.abs(Pmg[t])]
   

prob = cvx.Problem(obj, cons)
result1 = prob.solve(solver=cvx.ECOS) # expected: 5077.5
print result1
print prob.status
```

**Comment by adomahidi** [comment]
@jaehyunp If I run this with the new version I get this:

It     pcost         dcost      gap     pres    dres     k/t     mu      step     IR
 0   +3.190e+03   -6.116e+04   +1e+05   2e-01   4e+00   1e+00   2e+01    N/A     1 1 -
 1   +3.275e+03   -7.470e+03   +2e+04   4e-02   7e-01   7e-01   5e+00   0.8185   1 1 1
 2   +3.372e+03   -7.658e+03   +2e+04   4e-02   7e-01   1e+00   5e+00   0.1517   1 1 2
 3   +3.378e+03   -7.776e+03   +2e+04   4e-02   7e-01   1e+00   5e+00   0.0074   2 2 2
 4   +3.393e+03   -7.605e+03   +2e+04   4e-02   7e-01   1e+00   5e+00   0.0075   2 2 1
 5   +3.503e+03   -8.023e+03   +2e+04   4e-02   7e-01   2e+00   5e+00   0.2846   1 2 3
 6   +3.635e+03   -7.239e+03   +2e+04   4e-02   7e-01   2e+00   5e+00   0.0817   2 3 1
 7   +3.452e+03   -5.039e+03   +2e+04   3e-02   5e-01   2e+00   4e+00   0.4487   1 1 1
 8   +3.527e+03   -6.190e+03   +2e+04   4e-02   6e-01   3e+00   4e+00   0.0326   2 2 2
 9   +4.370e+03   -1.256e+03   +8e+03   2e-02   3e-01   2e+00   2e+00   0.8442   2 2 1
10   +4.554e+03   -6.663e+02   +5e+03   2e-02   3e-01   3e+00   1e+00   0.5235   2 2 2
11   +4.498e+03   +2.332e+03   +2e+03   8e-03   1e-01   1e+00   6e-01   0.9890   1 2 2
12   +4.746e+03   +3.944e+03   +8e+02   3e-03   5e-02   5e-01   2e-01   0.7198   2 2 1
13   +4.881e+03   +4.233e+03   +6e+02   2e-03   4e-02   4e-01   1e-01   0.5991   2 2 2
14   +5.002e+03   +4.821e+03   +2e+02   7e-04   1e-02   1e-01   4e-02   0.7945   2 2 2
15   +5.058e+03   +5.013e+03   +4e+01   2e-04   3e-03   3e-02   1e-02   0.8904   2 3 2
16   +5.073e+03   +5.064e+03   +9e+00   3e-05   6e-04   6e-03   2e-03   0.8155   2 3 2
17   +5.077e+03   +5.076e+03   +1e+00   5e-06   8e-05   9e-04   3e-04   0.8831   2 3 2
18   +5.077e+03   +5.077e+03   +3e-01   1e-06   2e-05   2e-04   7e-05   0.8291   2 2 2
19   +5.078e+03   +5.077e+03   +7e-02   3e-07   4e-06   5e-05   2e-05   0.8694   1 2 2
20   +5.078e+03   +5.078e+03   +6e-03   2e-08   9e-07   4e-06   2e-06   0.9371   2 2 2
21   +5.078e+03   +5.078e+03   +2e-03   1e-08   3e-07   1e-06   4e-07   0.8498   3 3 3
22   +5.078e+03   +5.078e+03   +4e-04   7e-08   2e-07   3e-07   9e-08   0.9490   2 2 2
23   +5.078e+03   +5.078e+03   +9e-05   4e-08   1e-07   7e-08   2e-08   0.7864   3 3 3
24   +5.078e+03   +5.078e+03   +8e-05   3e-08   1e-07   5e-08   2e-08   0.3844   2 1 1
25   +5.078e+03   +5.078e+03   +1e-05   8e-09   5e-08   8e-09   3e-09   0.9305   3 3 3
26   +5.078e+03   +5.078e+03   +4e-06   3e-09   2e-08   3e-09   1e-09   0.8103   2 1 1
Slacks/multipliers leaving the cone, recovering best iterate (26) and stopping.

Close to OPTIMAL (within feastol=2.0e-08, reltol=8.3e-10, abstol=4.2e-06).
Runtime: 0.053363 seconds.

5077.52993137
optimal_inaccurate


Let me know if this is accurate enough (feastol=2.0e-08, reltol=8.3e-10, abstol=4.2e-06).

**Comment by jaehyunp** [comment]
Yes, that's accurate enough! Just out of curiosity, why does the solver return optimal_inaccurate?

**Comment by adomahidi** [comment]
It fails to solve to required accuracy (which is somewhere near 2e-8, I think), but it manages to solve to "reduced" accuracy.

**Comment by jaehyunp** [comment]
Ah, I see. We only require 5-6 significant digits anyway (5077.53), so it's totally fine.
