### ISSUE TITLE
mistaken infostring in python wrapper

### ISSUE THREAD

**Issue by steve3141** [embotech/ecos#79]
Due to the following code in ecosmodule.c, which ignores the possible addition of ECOS_INACC_OFFSET. Any exit code which has been thus modified will fall into the "default" case and result in "UNKNOWN PROBLEM". 

For example, exit code 10, which means "Close to Optimal solution found" is reported as "UNKNOWN PROBLEM IN SOLVER"

(I also note that for some reason there is no test for ECOS_FATAL... I assume the intent was to translate that into "UNKNOWN PROBLEM IN SOLVER" but it would be more clear to make it an explicit switch case.)

ecosmodule.c, beginning at line 538:
```
/* info dict */
  /* infostring */
  switch( exitcode ){
      case ECOS_OPTIMAL:
          infostring = "Optimal solution found";
          break;
      case ECOS_MAXIT:
          infostring = "Maximum number of iterations reached";
          break;
      case ECOS_PINF:
          infostring = "Primal infeasible";
          break;
      case ECOS_DINF:
          infostring = "Dual infeasible";
          break;
      case ECOS_NUMERICS:
          infostring = "Run into numerical problems";
          break;
      case ECOS_OUTCONE:
          infostring = "PROBLEM: Multipliers leaving the cone";
          break;
      default:
          infostring = "UNKNOWN PROBLEM IN SOLVER";
  }
```

**Comment by echu** [comment]
@steve3141, we should have fixed this a while ago. I'm going to go ahead and close this issue. Thanks for bringing it up!

**Comment by steve3141** [comment]
Thanks. Sorry I moved on and wasn't able to properly test your changes.Regards,Steve Steven Jaffe
steve_jaffe@yahoo.com
845 453 1000
